### ISSUE TITLE
Test code on Python 3

### ISSUE THREAD

**Issue by ocefpaf** [darribas/contextily#1]
@darribas the code is not being tested on Python 3. See https://travis-ci.org/darribas/contextily/jobs/160874632#L643

I have a PR here to fix that and fix a minor py3k compat issue, but it is pending the conda-forge package for `mercantile` to simplify the `.travis.yml` file.

**Comment by darribas** [comment]
Merged! Thanks very much @ocefpaf , this is great!!!
