### ISSUE TITLE
Support alternative tile provider

### ISSUE THREAD

**Issue by choldgraf** [darribas/contextily#10]
Not sure how common this is but `tile.stamen.com` seems to be down right now. Is there another well-known tile provider for this kind of thing? If so maybe it'd be worth supporting it as a suggested parameter for `url`

**Comment by darribas** [comment]
Mmm... I've always had success with Stamen tiles. Maybe OpenStreetMap? The way it's setup, `contextily` should play nicely with all tile providers that follow the same structure, which is most of them.

**Comment by ljwolf** [comment]
fwiw, I'd really recommend taking inspiration from the API on `ggmap::get_map`, where `provider` and `maptype` are provided, but only certain combinations are valid between provider & maptype. 

And, it definitely works to just throw 
`url='http://tiles.openstreetmap.com/tileZ/tileX/tileY.png'` 
or
`url='https://darkmatter.basemaps.cartocdn.com/dark_all/tileZ/tileX/tileY.png'` 
so, should be a matter of following/updating what's in the [OSM wiki tile list]( https://wiki.openstreetmap.org/wiki/Tiles)?

**Comment by knaaptime** [comment]
there's a great list of tile providers [here](http://leaflet-extras.github.io/leaflet-providers/preview/). I'd be happy to add them all to `tile_providers` in a PR, but is there a way to point directly at the [repo](https://github.com/leaflet-extras/leaflet-providers)?

**Comment by darribas** [comment]
That is a really good resource @knaaptime!!! A suggestion: we could write a parser for [`leaflet-providers.js`](https://github.com/leaflet-extras/leaflet-providers/blob/master/leaflet-providers.js) that everytime is called goes to the original file on the web (the raw version of the link), and parses them, returning a `dict` with key for the name of the provider and the value for the url template, or something like that. That way, if the file is updated, we always pull the latest available. Does this make sense? PRs super welcome :-)

**Comment by knaaptime** [comment]
i spent some time trying to give the parser a shot today. It's a bit tricky since it's javascript not JSON, so the dict keys arent quoted. 

I haven't cracked it quite yet, but it could probably be accomplished with either (1) a clever regex, or (2) using a js parsing library like [slimit](https://github.com/rspivak/slimit) and a better recursive function than I could come up with to expand the sub-dicts

**Comment by jorisvandenbossche** [comment]
There is also a nice source (in Python code format) in the ipyleaflet package: https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/basemaps.py

I actually also quite like there dict approach (or could also be a named tuple), so we could consider basically copying it.

**Comment by darribas** [comment]
Yes, I like the dict approach too. Although, looking at both, @knaaptime's suggestion has a lot more sources. If we could crack how to parse dynamically that `.js` file, I think it'd be ideal. Then we could take a similar dict approach for returning it to the user?

**Comment by jorisvandenbossche** [comment]
I think we still want to hardcode the values inside the contextily package, and not parse it on the fly? 

So we could still have a script to parse that file to have more sources (and can re-run that from time to time), but output something like the .py file with dicts to include in the source.

**Comment by darribas** [comment]
Yeah, that might be a sensible approach. My thought was that `contextily` requires connectivity anyway and they might keep the list updated, so that'd work. But might be safe to keep a local copy of the addresses. What do other folks feel like?

**Comment by jorisvandenbossche** [comment]
For me, good reasons to have a local copy are:

- doesn't depend on the availability of that source page in specifics (in case of github down, file rename, ..)
- doesn't depend in general on connectivity: you can use contextily offline (with images from disk or (in future) cached tiles)

and then I would personally include an actual python file instead of the js file as is, because it is more transparent (you see the python data structures that will be exposed in the source code) and a python file is also more more readable IMO (I would typically want to look at this file to see what the different sources are).

**Comment by jorisvandenbossche** [comment]
I started with a script parsing the leaflet-providers.js defined sources, and converted that now to a standardized JSON from which we can start in contextily, see #66

Then, the more important question is how to expose this in the python contextily interface? I could do something similar as https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/basemaps.py, automatically creating such objects from the parsed JSON. 

Another question is how the user can override certain keys, if needed (eg some need an access token or api key, see some examples in javascript here https://github.com/leaflet-extras/leaflet-providers#here-formerly-nokia)

**Comment by jorisvandenbossche** [comment]
I think this is closed by https://github.com/darribas/contextily/pull/66
