### ISSUE TITLE
Extraneous test requirements in runtime requirements

### ISSUE THREAD

**Issue by QuLogic** [darribas/contextily#122]
The runtime requirements include `pytest`, but that is not used at runtime, and seems extraneous.

**Comment by darribas** [comment]
Thanks for the report! Yes, `pytest` is what we use on our testing suite. @jorisvandenbossche maybe we could move that to `requirements_dev` instead? If memory serves, I put everything on one file as it was easier to get the project off the ground, but would be happy to split.

**Comment by jorisvandenbossche** [comment]
I don't think this is still the case? https://github.com/darribas/contextily/blob/master/requirements.txt

@QuLogic Are you using a version from PyPI, or from github master?

**Comment by QuLogic** [comment]
Ah, from PyPI yes, it does appear to have changed on master.
