### ISSUE TITLE
Release 0.99

### ISSUE THREAD

**Issue by darribas** [darribas/contextily#14]
Cut release and push to `pypi` and `conda-forge`.

**Comment by darribas** [comment]
In order to push a new version to conda-forge, what should I do @ocefpaf ? Thank you very much for all the support with this.

**Comment by ocefpaf** [comment]
In theory all you need to do is to change the [version](https://github.com/conda-forge/contextily-feedstock/blob/3e90a6e2df52441ff7d3302f245c9cb5f8109617/recipe/meta.yaml#L1)  and the [checksum](https://github.com/conda-forge/contextily-feedstock/blob/3e90a6e2df52441ff7d3302f245c9cb5f8109617/recipe/meta.yaml#L10) in the recipe. With a PR from your fork. I'm updating the feedstock with the latest conda-forge changes now to get ready for that.

**Comment by darribas** [comment]
OK, release is up on PyPi! I've updated the recipe and issued the PR. I'm waiting on the CI but I suspect it'll fail as it tests on Python 3.4 as well, which we dropped support for because there was a glitch that made it fail. What do you recommend?

As soon as this is sorted and 0.99 is on `conda-forge`, we can maybe write a short blog post to go at https://geographicdatascience.com/blog/ (or somewhere else!). @choldgraf would you want to have a go at drafting a short one with what is new (all the stuff you've put in)?

**Comment by ocefpaf** [comment]
> What do you recommend?

We can make the recipe `noarch` and forget about that. I just updated it to reflect that change.

**Comment by darribas** [comment]
Fantastic! Does this mean 0.99 is live on `conda-forge`? A quick search doesn't pick it up yet:

```
dh073211:~ dani$ conda search -c conda-forge contextily
Fetching package metadata ...........
contextily                   0.9.0                    py27_0  conda-forge
                             0.9.2                    py27_0  conda-forge
                             0.9.2                    py34_0  conda-forge
                             0.9.2                    py35_0  conda-forge
                             0.9.2                      py_0  conda-forge
dh073211:~ dani$
```

**Comment by ocefpaf** [comment]
No, we need to merge https://github.com/conda-forge/contextily-feedstock/pull/5 (just did BTW).

It should be live in a few minutes.

**Comment by choldgraf** [comment]
hooray! I could help w/ a blog post but it'll be a little bit of time as I don't have a lot of bandwidth right now. Is there a timetable on this?

**Comment by darribas** [comment]
@choldgraf Thanks! No, not real rush. I think the key point, which was to get a version out there that passes CI is already satisfied. The blog post is more to let people know about it, but it's not a huge rush I'd say. Do you want to have a first go at it when you can and let me know? I'll be happy to chip in. Thank you very much for all your contribution and support to the library!

**Comment by darribas** [comment]
@choldgraf, just checking in, any updates on the potential blog post? Happy to have a look and edit later on.

**Comment by darribas** [comment]
No worries, I think I understand :) Yeah, this is from the previous (initial) release:

https://geographicdatascience.com/2016/10/07/contextily-context-geo-tiles-in-python/

Very short and to the point. I think the idea with the new release would be to stress what's new (the `Place` API) and point to the example you have. It's mostly so we have something to bother the Twitterverse with :D

**Comment by darribas** [comment]
OK Pushed the release this morning:

> https://github.com/darribas/contextily/releases/tag/v0.99.0

And have drafted a release blog post:

> https://gist.github.com/darribas/9907cc32fa130dd886a7fa0f04ce9b76

@choldgraf can you please have a look at change as desired (or suggest changes)? When we're both happy, I'll post it to our lab's blog:

> https://geographicdatascience.com/blog/

Unless you have a better outlet (to which I'm very open to!).

Let me know,

]d[

**Comment by darribas** [comment]
I can't seem to add images to gist so I'll post here, this is the image the example in the post should return:

![berkeley](https://user-images.githubusercontent.com/417363/32274818-9c377428-bf00-11e7-81eb-8c6674f29e90.png)

**Comment by choldgraf** [comment]
Yo! looks good to me, a couple quick comments:

> We have also updated the main guide notebook so be sure to check it out to find out all that is possible with

It seems to tail off here. Maybe you mean to say "possible with Contextily"?

> And you can quickly plot it with the newly added plot_map function:

I think it'd be worth highlighting that you can plot other geodata on top. Maybe just grab the lattitutde longitude of Doe Library and plot it as a star or something?

> quickly pulling down

quickly pull down.


Also, re posting, we could cross-post it with the BIDS blog perhaps? If so I can shoot a draft of the post by our communications lady who might have comments of her own. Let me know what you think!

**Comment by darribas** [comment]
Hey! Updated, thanks very much for catching those. Yeah, the BIDS cross-post sounds great, we should be able to get quite a bit of attraction through that. Let me know if I can do anything to help on that.
]d[

**Comment by darribas** [comment]
@choldgraf Just checking this is not waiting on me on doing anything. As soon as we're happy with it and see if BIDS can post too, I can post it at the GDSL site :)

**Comment by choldgraf** [comment]
Hey - nope not waiting on you or me. I spoke to the BIDS blog person and
they said it'd be more appropriate if I wrote up something more about my
perspective etc. I don't have time to do that right now, so I think we
should just post it and I'll ping you when I can get a follow-up post up
there. Does that work?
--

**Comment by darribas** [comment]
Cool! I'll pass it on for publication here then!

**Comment by darribas** [comment]
Closing as this was released already. We're now planning [1.0](https://github.com/darribas/contextily/milestone/1) 😄

**Comment by choldgraf** [comment]
🎉 🎉 🎉
