### ISSUE TITLE
pixelated images

### ISSUE THREAD

**Issue by choldgraf** [darribas/contextily#15]
Oftentimes the images that contextily grabs are quite pixelated. I haven't found a good way to download less-pixelated images other than increasing the `zoom` level, which generally makes the download take waaaay longer. Do you have any tips for getting the same zoom level, but at a higher resolution?

**Comment by choldgraf** [comment]
cc @lwasser as I know she was curious about this too

**Comment by lwasser** [comment]
ahhh yes @choldgraf  @darribas i played around with the zoom and that didn't fix the issue which is when i create a larger figure, the map is then pixelated. Is this user error on my end?

**Comment by darribas** [comment]
Mmm... not directly, the way `contextily` works, every tile has the same size (248x248 if memory serves well) and the zoom controls how many tiles are used for a given extent. I'm not sure how you'd fix that or if it relates to `contextily` or the tile provider. Have you seen a different library working, for instance `ggmap` in R?

**Comment by lwasser** [comment]
You know, I've used ggmap a good bit but never looked under the hood to see how they are grabbing tiles. I'll dig a bit more to try to understand how it works so I can be more helpful here. Thanks so much.

Leah A. wasser

**Comment by jorisvandenbossche** [comment]
I was looking into this a bit, and I think doing interpolation in `imshow` is the best we can get to somewhat solve the pixelated view (it does not solve that you actually might want a higher resolution at a given zoom level ..).

Small example, for Berlin at zoom level 10, the original version (if you only do `plt.imshow(basemap, extent=extent)`):

![image](https://user-images.githubusercontent.com/1020496/39784287-30ae97f2-5318-11e8-852a-c7791c85da0c.png)

And with `interpolation='bilinear'`:

![image](https://user-images.githubusercontent.com/1020496/39784296-37c3ef74-5318-11e8-97df-191d72d0a64f.png)

Which gives a bit better result I think (but as I said, does not give a higher resolution image, only makes the current one a bit nicer). 
I *think* this is also what `ggmap` does, from a quick view on their source code (but no expert on that)

**Comment by choldgraf** [comment]
Nice - that would make sense to me as well...I was wondering how ggmap would get a smoother result from the same underlying data

**Comment by jorisvandenbossche** [comment]
@choldgraf see also https://github.com/darribas/contextily/issues/20, if you have an opinion on that

**Comment by ljwolf** [comment]
playing around with all the methods, I think `sinc` interpolation gives a marginally sharper image, over `bilinear`, since it appears to strongly preserve contrast better:
![2018-05-11-092940_1112x835_scrot](https://user-images.githubusercontent.com/2250995/39914739-d9a118da-54fd-11e8-821b-bc2b147b62a2.png)
![2018-05-11-092935_1093x831_scrot](https://user-images.githubusercontent.com/2250995/39914742-dad02caa-54fd-11e8-9522-02ca36e44544.png)
But, this is messing at the margins, since `interpolation='none'` looks pixelated regardless of setting `axes=equal`.

**Comment by choldgraf** [comment]
+1 with sinc interpolation (you could always make this a kwarg)

**Comment by lwasser** [comment]
Wow!! This is visually a lot nicer with the interpolation ! Happy to see this is being revisited. I still haven't looked closely at ggmap to understand how to works.  Will this be implemented in contextily? If so I'll try it again for my course! Thank you all!

**Comment by ljwolf** [comment]
I think this would be what we set as defaults for #20

**Comment by lwasser** [comment]
hi all! i'm revisiting this again as i'm working on my class - again. just curious how or whether this might become the default behaviour for contextily plotting. For now i'm happy with using imshow to interpolate. Look at the difference!

BEFORE interpolation
<img width="578" alt="screen shot 2018-07-03 at 4 12 05 pm" src="https://user-images.githubusercontent.com/7649194/42246947-e115329c-7edb-11e8-808b-3486fd9edac3.png">

after: 
<img width="681" alt="screen shot 2018-07-03 at 4 12 42 pm" src="https://user-images.githubusercontent.com/7649194/42246964-f2cf66c4-7edb-11e8-866a-dbf33411001d.png">

it would be a nice default plotting behavior if not already implemented. But i do appreciate and thank you all for demonstrating how the maps can be cleaned up using the imshow args.

If this has been implemented please let me know and we can also close this issue :)

**Comment by knaaptime** [comment]
the interpolation is included as default in 4850849 but hasn't been merged/released

**Comment by lwasser** [comment]
ok so install from github in the meantime as an alternative? Thank you @knaaptime ! This is a really nice fix.

**Comment by knaaptime** [comment]
sure, but i'm just the messenger. the credit goes to @ljwolf :)

so the quickest way to use it is to install from his fork until this gets merged

**Comment by ljwolf** [comment]
I won't speak for @darribas & am not a project maintainer, but I think that #21 may have stalled because of the auto-zoom request in #5, mentioned in #20. 

Personally, I don't know if I'll have time to take a look at this until [SciPy](https://scipy2018.scipy.org/ehome/index.php?eventid=299527&), but I'll try to un-stick #21 by then.

**Comment by darribas** [comment]
Quick update. @ljwolf and I are at SciPy and the idea is to cut a release that includes the interpolation, as well as some streamlining of the API (hopefully not back-breaking :) ). More to come soon!

**Comment by lwasser** [comment]
oh wonderful. thank you for the update @darribas  :) yay!

**Comment by darribas** [comment]
This is now addressed in #32, so it's ready in `master`, should be getting out as a new release soon. If you need it urgently, you can `pip install` against `master`.

**Comment by lwasser** [comment]
i know this is closed but just writing to  thank you again @darribas  :)
