### ISSUE TITLE
[ENH]: backoff parameter? 

### ISSUE THREAD

**Issue by ljwolf** [darribas/contextily#34]
Sometimes, if you hit APIs for too many tiles, the API will ratelimit. 

It would be nice if there were a rudimentary support for a wait time within `bounds2*` functions, so that you could specify a number of seconds to wait between tile queries & a `max_retries` amount.

**Comment by darribas** [comment]
This sounds good. Would there be any disadvantage? would defaults make it work in the same way as right now?

**Comment by jorisvandenbossche** [comment]
Somewhat related (as it can also help with rate limits), would be an automatic caching of downloaded tiles.

**Comment by darribas** [comment]
Related to #46

**Comment by darribas** [comment]
If I read it correctly, this was included in #35. Closing as implemented, but feel free to reopen otherwise.
