### ISSUE TITLE
Adding option to restrict `ax` extent to original one when using `add_basemap`

### ISSUE THREAD

**Issue by darribas** [darribas/contextily#45]
When a user adds a basemap with `add_basemap`, the extent of the returned figure is automatically reset to fit that of the merged tiles. In some cases, this can render the original data in a too small part of the map. It'd be nice if `add_basemap` could take an argument `reset_extent` set to `False` by default to maintain original behaviour that made sure the outcoming figure had the same extent of the incoming `ax` object.

**Comment by ljwolf** [comment]
This resetting of extent also annoys me often when it happens...

Should be two lines to pull off the axis at the start and put it back on at the end.

**Comment by darribas** [comment]
Quick update on this: I've had a look at #38 and looks good except an error that comes up on one test. I have also added the option to not reset the extent in case the user so wants (not the default). Once these two minor issues are ready to go, I'm happy to merge the PR.
