### ISSUE TITLE
Add auto-zoom

### ISSUE THREAD

**Issue by darribas** [darribas/contextily#5]
There could be an `'auto'` option for the `zoom` argument. This would use `howmany` under the hood and pick the greatest zoom that had to download less than X tiles (e.g. 30).

**Comment by darribas** [comment]
@choldgraf has implemented an [`auto_zoom`](https://github.com/darribas/contextily/blob/master/contextily/place.py#L153) but needs to be added as default for `bounds2img` and `bounds2raster` to let the user not have to pass an explicit `zoom` level.

**Comment by ljwolf** [comment]
What happens to the latlong/webmercator specificity? Do we still support `latlong=True`?

**Comment by ljwolf** [comment]
indeed, `calculate_zoom is done directly in latlong, not webmerc

**Comment by darribas** [comment]
This is included in #32
