### ISSUE TITLE
Add Python 3.7 to testing suite, maybe remove 3.5?

### ISSUE THREAD

**Issue by darribas** [darribas/contextily#54]

**Comment by jorisvandenbossche** [comment]
A further suggestion for the CI: we could also create a few actual environment files (similarly as I did for geopandas: https://github.com/geopandas/geopandas/tree/master/ci/travis, but then not that many). 
That way, we can also test different versions of dependencies (to ensure everything works with the minimal versions we say to support), as opposed to only the latest versions now.

**Comment by jorisvandenbossche** [comment]
BTW, happy to do a PR for this, if that is desired.

**Comment by darribas** [comment]
Nice! I thought we were already testing on Python 2 and 3 already. Just to get my head around it, this would expand that approach to a few more setups? I think that'd be good in principle. How hard to maintain would it be?

**Comment by jorisvandenbossche** [comment]
> How hard to maintain would it be?

In itself, it's not much harder to maintain. It would just create a few environment yml files next to the requirements.txt. 
But of course, properly testing "oldest supported" versions will give more maintenance work than only testing the latest versions. But we can be quite aggressive in bumping minimum versions (currently we don't really specify that, so that would be a first thing to do)

**Comment by darribas** [comment]
I like that idea. Maybe we should rather than commit to support many versions, say that they might work but be explicit about which ones we do support and what's our philosophy (ie. support the latest ones best until they fail for lack of support upstream)?

**Comment by darribas** [comment]
Thinking on this. I'd drop 3.5 for now so all tests are back to green and, if we find bandwidth, we can add a more comprehensive testing framework later on. I'm not too worried about supporting older versions as `contextily` is probably used most at the end of the pipeline in an interactive way, so users would access it on the standard version, which I'd imagine aligns pretty well with whatever Anaconda is distributing (and `conda-forge` supporting) at the moment. What do you think on dropping 3.5 for now @jorisvandenbossche? On the more comprehensive approach, of course, PRs most welcome! :-)

**Comment by darribas** [comment]
Fixed with #81
