### ISSUE TITLE
Explore `pytest` errors

### ISSUE THREAD

**Issue by darribas** [darribas/contextily#56]
Focused on Python 3.5. For [example](https://travis-ci.org/darribas/contextily/jobs/481372826).)

**Comment by jorisvandenbossche** [comment]
So it's a failure to install rasterio correctly (and not a pytest issue), see https://github.com/conda-forge/gdal-feedstock/issues/261

**Comment by jGaboardi** [comment]
seems to be an issue with [`Python 3.5` support](https://github.com/darribas/contextily/pull/63#issuecomment-474592349)

**Comment by darribas** [comment]
Should we then drop support for Python 3.5? What do people think? @jorisvandenbossche @ljwolf @jGaboardi

**Comment by jorisvandenbossche** [comment]
I don't have a strong opinion (until recently I was still using py 3.5 for development, but switched now to python 3.7). Conda-forge no longer supporting it is a good reason to drop it. But if we find a good solution for testing / CI to include 3.5 (eg use pip for some packages), I also don't think it is hard to still keep it for a while (unless we want to start using python >= 3.6 features)

**Comment by darribas** [comment]
My main motivation is ease of maintenance. I'd rather avoid keeping different setups for different versions tbh, but if anyone wants to volunteer to keep it, I won't stop it...

**Comment by jorisvandenbossche** [comment]
@darribas this one can be closed now
