### ISSUE TITLE
Use standard urls with {x} instead of 'tileX'

### ISSUE THREAD

**Issue by jorisvandenbossche** [darribas/contextily#60]
As far as I am aware, it's common that urls are given in "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" format, instead the "tileZ/tileX/tileY" pattern we use in contextily. At least that is what I see used in leaflet based ones, and is also closer to the python formatting syntax. 

What do you think to switch to that? (and we can certainly still support both in the beginning (to deprecate the current version) or even in the long term)

**Comment by darribas** [comment]
Sounds like a good idea. It's not a big deal either way, but it'd help align `contextily` with other web mapping formats (and that might mean easier pulling in of other sources, as we discuss in #10 ).

**Comment by darribas** [comment]
Also, as I'm going over this again, it'd be great to get in before we issue a 1.0 as I'd like that to have a stable stable API.
