### ISSUE TITLE
update Miniconda2 to Miniconda3

### ISSUE THREAD

**Issue by jGaboardi** [darribas/contextily#62]
[Failures in Python 3.5](https://travis-ci.org/darribas/contextily/jobs/484776634) may be remedied by swapping out Miniconda2 for Miniconda3 with building TravisCI test environments.

This was part of the solution for correcting the [`segmentation fault: code 139` error](https://github.com/pysal/splot/pull/48#issuecomment-474466786) in [`pysal/splot`](https://github.com/pysal/splot/issues/47) that we were seeing.

**Comment by jorisvandenbossche** [comment]
I don't think the failures are related to that. Because we create a new environment with a specific python version anyway (with https://github.com/darribas/contextily/blob/master/.travis.yml#L19). 

But, that said, it is certainly a good idea to switch to download the Miniconda3 version.

**Comment by jGaboardi** [comment]
@jorisvandenbossche yep, it did not completely fix the issue as it did in `splot`. Now [`rasterio` seems to causing issues](https://travis-ci.org/darribas/contextily/jobs/508509779), both with and without `- conda config --set channel_priority strict`

**Comment by jGaboardi** [comment]
related to #54

**Comment by jorisvandenbossche** [comment]
To repeat what I said above: updating to Miniconda3 is a good idea, but it is not related to testing of python 3.7 or not (since we create new environments anyway and don't use the base miniconda install)

**Comment by jGaboardi** [comment]
Miniconda update resolved.
