### ISSUE TITLE
Lack of User-Agent header viiolates OSM usage policy

### ISSUE THREAD

**Issue by szmoore** [darribas/contextily#75]
In `tile._retryer` the request is sent without a `User-Agent` header.
Previously I'd had no issues, however recently I started getting `403: Forbidden` responses from OSM. Reading their [usage policy](https://operations.osmfoundation.org/policies/tiles/) reveals that this header is required:

> Valid HTTP User-Agent identifying application. Faking another app’s User-Agent WILL get you blocked.

It's possible this is a recent update, since I don't remember reading that earlier, or maybe they are just a bit lenient until you exceed a usage rate.

I was able to bypass the error by simply adding a `User-Agent: contextily` header.
However, I think to properly meet the usage requirements, this header needs to be set by the user of `contextily` to actually identify their app.

**Comment by szmoore** [comment]
Of course, requests provides a default user agent
https://evanhahn.com/python-requests-library-useragent/

There is a possibility that my particular usage of contextily+OSM has made them auto-ban the default requests user-agent... I hope not... but I am sorry to everyone inconvenienced if that is the case.

**Comment by ljwolf** [comment]
should be real easy to use a specific user-agent string for contextily in the [`_retryer`](https://github.com/darribas/contextily/blob/master/contextily/tile.py#L194).... but if we want to support custom useragent strings, we may need to think about more [advanced features](https://2.python-requests.org/en/master/user/advanced/#session-objects)

**Comment by darribas** [comment]
There's a (temporary) fix for this brought in with #81. Closing for now, but we can reopen if needed.
