### ISSUE TITLE
Error in generating base map

### ISSUE THREAD

**Issue by ruvenguna** [darribas/contextily#78]
I have this code:

    import pandas as pd
    import numpy as np
    from geopandas import GeoDataFrame
    import geopandas
    from shapely.geometry import LineString, Point
    import matplotlib.pyplot as plt
    import contextily
    
    ''' Do Something'''

    df = start_stop_df.drop('track', axis=1)
    crs = {'init': 'epsg:4326'}
    gdf = GeoDataFrame(df, crs=crs, geometry=geometry)
    
    ax = gdf.plot()
    contextily.add_basemap(ax)
    ax.set_axis_off()
    plt.show()

Basically, this generates a background map that is in Singapore. However, when I run it, I get the following error: `HTTPError: Tile URL resulted in a 404 error. Double-check your tile url:http://tile.stamen.com/terrain/29/268436843/268435436.png`
However, it still produces this image:
[![Code output][1]][1]

How can I change the Tile URL? I would still like to have the map of Singapore as the base map. 

**EDIT**:   
Also tried including this argument to add_basemap:   
`url ='https://www.openstreetmap.org/#map=12/1.3332/103.7987'`  
Which produced this error:  
`OSError: cannot identify image file <_io.BytesIO object at 0x000001CC3CC4BC50>`
I am running on contextily version 1.0rc1

  [1]: https://i.stack.imgur.com/p9YSD.png

**Comment by darribas** [comment]
Just to be clear @ruvenguna, did you manage to solve the issue?

**Comment by ruvenguna** [comment]
Hello!

Thank you for your email. Yup I managed to get it to work. I changed the CRS used and it worked! I wanted to delete my post but I wasn’t sure how to.

Thanks for asking!

Regards,
Ruven Guna
________________________________

**Comment by jhconning** [comment]
I am having the exact same problem, trying to adapt the [example from geopandas docs](
http://geopandas.org/gallery/plotting_basemap_background.html#sphx-glr-gallery-plotting-basemap-background-py)

  Can you explain how you were able to resolve this issue?

```
pserf.crs
{'init': 'epsg:4326'}
```
```
ax = pserf.plot(figsize=(10,10))
ctx.add_basemap(ax)
```

This produces an error that ends with

```
...
HTTPError: Tile URL resulted in a 404 error. Double-check your tile url:
https://stamen-tiles-a.a.ssl.fastly.net/terrain/23/4194302/4194300.png
```

It plots the geodataframe but can't find the png file at the URL.

**Comment by darribas** [comment]
Thanks for reporting @jhconning. What version are you using? For older versions, you'll have to make sure your data are expressed in [Web Mercator](http://epsg.io/3857):

```python
ax = pserf.to_crs(epsg=3857).plot(figsize=(10,10))
ctx.add_basemap(ax)
```

If you have `1.0rc2`, you can warp the tiles instead by doing:

```python
ax = pserf.plot(figsize=(10,10))
ctx.add_basemap(ax, crs=pser.crs)
```

Feel free to report back if you have any issues.

**Comment by jorisvandenbossche** [comment]
I think we should try to detect this case and provide a better error message. We can know that certain x,y,z values can never occur in practice.

Eg in the first case: "HTTPError: Tile URL resulted in a 404 error. Double-check your tile url:http://tile.stamen.com/terrain/29/268436843/268435436.png". Such a high zoom value never occurs

**Comment by jorisvandenbossche** [comment]
With the new providers API we actually also know the max zoom supported by a provider, so we should use that.
